### REQUIRED ARGUMENTS BY USER
rawdir:
  '/data'
output_dir:
  '/results'

group1: [
  'sample1'
]
group2: [
  'sample2'
]
samples: [
  'sample1',
  'sample2',
]
ref:
  '/app/reference/homo_sapiens.GRCh38.dna.primary_assembly.fa'

gtf_annotation_file:
  '/app/annotation/Homo_sapiens.GRCh38.110.gtf'
  
computing_threads:
  8
